export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const SWITCH_CARSET = "SWITCH_CARSET";

export const REQUEST_ROBOTS_PEDDING = "REQUEST_ROBOTS_PEDDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAIL = "REQUEST_ROBOTS_FAIL";

//async call normally has 3 state
